### PR TITLE
Removed some repositories

### PR DESCRIPTION
**Pull request by fayasnoushad**

### CODE REVIEW

**Comment by rojvv** [comment]
`callsmusic/tgvc-userbot` isn't archived.

**Comment by fayasnoushad** [comment]
> `callsmusic/tgvc-userbot` isn't archived.

Check the commit, `Yeagerist-Music-Streamer-Bot-V3/YuiHirasawaMusicBot` is archived.

**Comment by rojvv** [comment]
@FayasNoushad *I talk about* `callsmusic/tgvc-userbot`. It is not archived.

**Comment by fayasnoushad** [comment]
> @FayasNoushad _I talk about_ `callsmusic/tgvc-userbot`. It is not archived.

Yeah I know that. I'm not removed that.

**Comment by rojvv** [comment]
Remove it from your commit messages, at least.

**Comment by fayasnoushad** [comment]
> Remove it from your commit messages, at least.

[Its archived now](https://github.com/tgcalls/awesome-tgcalls/pull/44/commits/6b55bd39bb90b7dba8abd2c112bacfb9758cd391) commit for `Yeagerist-Music-Streamer-Bot-V3/YuiHirasawaMusicBot`. Its not for `callsmusic/tgvc-userbot`

**Review by fayasnoushad — COMMENTED** [review]
Please check the [changes](https://github.com/tgcalls/awesome-tgcalls/pull/44/files) and please merge.

**Comment by rojvv** [comment]
Run the following commands in your fork, so your commits are cleaned:
- `git reset --soft bbfa47076b8deeb5ec761dc40b6df9eee00d2c72`
- `git commit -m 'Remove archived repositories'`
- `git push -f`

After that, I’ll approve.

**Comment by fayasnoushad** [comment]
> Run the following commands in your fork, so your commits are cleaned:
> 
> * `git reset --soft bbfa47076b8deeb5ec761dc40b6df9eee00d2c72`
> * `git commit -m 'Remove archived repositories'`
> * `git push -f`
> 
> After that, I’ll approve.

You can squash merge

**Comment by rojvv** [comment]
Actually, I don't even have the right to merge. But I can help the ones who can merge if I approve.

**Comment by fayasnoushad** [comment]
> Actually, I don't even have the right to merge. But I can help the ones who can merge if I approve.

Ok, The maintainer can squash merge ( merge as one commit ).

**Comment by rojvv** [comment]
I don't think so, you can just do it from your side with a single enter. The owner won't bother his time fixing your commit messages.

**Comment by MarshalX** [comment]
Why did you remove https://github.com/AsmSafone/VideoPlayerBot?

**Comment by fayasnoushad** [comment]
> Why did you remove https://github.com/AsmSafone/VideoPlayerBot?

Same of `subinps/VCPlayerBot`

Original repository :- https://github.com/subinps/VCPlayerBot
More Information and proof :- https://t.me/subin_works/204

**Pull request closed without merging**
