### PR TITLE
Added Video Player Bot

### PR DESCRIPTION
**Pull request by AsmSafone**

### CODE REVIEW

**Comment by MarshalX** [comment]
README.md:72:125
9
  ✖  72:125  Text "youtube" should be written as "YouTube"  remark-lint:awesome-spell-check

**Comment by tgvc** [comment]
> README.md:72:125
> 9
> ✖ 72:125 Text "youtube" should be written as "YouTube" remark-lint:awesome-spell-check

ok

**Comment by AsmSafone** [comment]
> README.md:72:125
> 9
> ✖ 72:125 Text "youtube" should be written as "YouTube" remark-lint:awesome-spell-check

ok

**Comment by MarshalX** [comment]
Thanks

**Pull request merged**
