### PR TITLE
Remove broken links

### PR DESCRIPTION
**Pull request by ni5arga**
Those repo links are broken as the callsmusis org no longer exists

### CODE REVIEW

**Comment by rojvv** [comment]
They're not broken. Calls Music org still exists. It's just hidden from public atm.

**Comment by MarshalX** [comment]
> They're not broken. Calls Music org still exists. It's just hidden from public atm.

But links doesn’t work for me too…

**Comment by rojvv** [comment]
@MarshalX maybe you can give us some time, we might move to GitLab soon.

Also, you might change the links to these (temporarily): https://t.me/CallsMusicUpdates/48

**Comment by rojvv** [comment]
#35

**Comment by MarshalX** [comment]
fixed in #35, thanks

**Pull request closed without merging**
